### ISSUE TITLE
Preprocessing of Build-in function arguments

### ISSUE THREAD

**Issue by szsascha** [worksofbarry/NetRPG#17]
I just created the build-in function %subst (Substring). Following things are not working. I think these things should be processed on a higher level and not in the substring implementation because in other bif's are similar problems.

Case 1: Use substring to change values (working on i)

```
resultb = 'Hello';
%subst(resultb:1:1) = 'D';
```

resultb is still "Hello" and not "Dello"

Case 2: Preprocessing of arguments (working on i)

`resultb = %subst('Hello World':5+2:10-7);`

Failing because of calculations in the second and third argument.

**Comment by worksofliam** [comment]
Hi

1. I made a comment here (`//TODO`) indicating that this is something I was going to work on at some point: https://github.com/worksofbarry/NetRPG/blob/master/NetRPG/Language/Reader.cs#L687
2. I just made something to fix this but I must have forgotten to implement for internal functions.

I will create unit tests for both of these issues and then implement fixed in two separate commits.

Liam

**Comment by worksofliam** [comment]
Found the issue. It's in the parser:

![image](https://user-images.githubusercontent.com/3708366/64141513-f1c94500-cdcd-11e9-8f5e-33185a59dda4.png)

**Comment by worksofliam** [comment]
@SaschaS93 I believe I made a fix and a unit test to go along with it.

You can see it at commit d83e7d430760278edf8857a8d6e28bbd4aef3af8.

Please can you make a unit test for assigning to a substring whenever you have a moment?

Thanks!
